// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbTutNc1L1Ii9kZiw7cc3doV0SwyM7dk',
    appId: '1:634373545211:web:c83775b278375b6bb6245e',
    messagingSenderId: '634373545211',
    projectId: 'fir-flutter-codelab-1b72b',
    authDomain: 'fir-flutter-codelab-1b72b.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-1b72b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpy7ZACAFFDWuG4BHZpdXg7x68h7oDu6U',
    appId: '1:634373545211:android:69214ca7542f97e9b6245e',
    messagingSenderId: '634373545211',
    projectId: 'fir-flutter-codelab-1b72b',
    storageBucket: 'fir-flutter-codelab-1b72b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi4f8L7X9r9GaXuieEkJox6yK6nGL72X0',
    appId: '1:634373545211:ios:ef0608485a35ffe6b6245e',
    messagingSenderId: '634373545211',
    projectId: 'fir-flutter-codelab-1b72b',
    storageBucket: 'fir-flutter-codelab-1b72b.appspot.com',
    iosClientId: '634373545211-5mpun98pohvnplufqe20abadinqa50sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi4f8L7X9r9GaXuieEkJox6yK6nGL72X0',
    appId: '1:634373545211:ios:ef0608485a35ffe6b6245e',
    messagingSenderId: '634373545211',
    projectId: 'fir-flutter-codelab-1b72b',
    storageBucket: 'fir-flutter-codelab-1b72b.appspot.com',
    iosClientId: '634373545211-5mpun98pohvnplufqe20abadinqa50sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
